parameters:
  DICTIONARY_WEB_DIR: '%kernel.project_dir%/src/*/UI/'
  dictionary_storage:
    en: '%kernel.project_dir%/data/english.txt'
    ru: '%kernel.project_dir%/data/russian.txt'

services:
  App\Dictionary\Infrastructure\Gateway\Adapter\WordDefinitionWikipediaApiGateway: ~

  App\Dictionary\Infrastructure\Gateway\Adapter\WordDefinitionGoogleApiGateway:
    calls:
      - setNext: ['@App\Dictionary\Infrastructure\Gateway\Adapter\WordDefinitionWikipediaApiGateway']

  App\Dictionary\Application\Service\WordsStoragePopulate:
    arguments:
      - '@App\Dictionary\Infrastructure\FileReader\TextFileReader'
      - '@command.bus'
      - '@monolog.logger'

  App\Dictionary\Application\Service\WordsStorageUpload:
    arguments:
        - '@App\Dictionary\Infrastructure\FileReader\CsvFileReader'
        - '@command.bus'
        - '@monolog.logger'

  App\Dictionary\Infrastructure\FileReader\TextFileReader: ~
  App\Dictionary\Infrastructure\FileReader\CsvFileReader: ~
  App\Dictionary\Infrastructure\Repository\Elastic\WriteWordsStorage: ~
  App\Dictionary\Infrastructure\Repository\Elastic\ReadWordsStorage: ~

  App\Dictionary\Domain\Port\WordDefinitionApiGatewayInterface: '@App\Dictionary\Infrastructure\Gateway\Adapter\WordDefinitionGoogleApiGateway'
  App\Dictionary\Domain\Repository\ReadWordsStorageInterface: '@App\Dictionary\Infrastructure\Repository\Elastic\ReadWordsStorage'
  App\Dictionary\Domain\Repository\WriteWordsStorageInterface: '@App\Dictionary\Infrastructure\Repository\Elastic\WriteWordsStorage'