version: '3.7'
services:
    web:
        build:
            context: docker/nginx
        container_name: game_web
        ports:
            - 1000:80
        volumes:
            - ./code:/var/www/html/code
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        links:
            - php
        networks:
            - game
    php:
        build: docker/php
        container_name: game_php
        volumes:
            - ./code:/var/www/html/code
        links:
            - elasticsearch
        networks:
            - game
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        container_name: game_es
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - ./docker/data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - game
    redis:
        image: redis
        container_name: game_redis
        command: [ "redis-server", "--appendonly", "yes" ]
        ports:
            - 6379:6379
        networks:
            - game
        volumes:
            - ./docker/data/redis:/data
    rabbit:
        image: "rabbitmq:3-management"
        container_name: game_rabbit
        environment:
            RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
            RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
            RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
            RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
        ports:
            - 1004:15672
            - 1005:5672
        volumes:
            - ./docker/rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins"
        networks:
            - game
    newman:
        build: docker/newman
        container_name: game_newman
        command:
            run postman_collection.json --insecure
            -e postman_environment.json
            -r cli
        links:
            - web
        volumes:
            - ./postman:/etc/newman
        networks:
            - game
networks:
    game:
        name: game
