doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        types:
            playerId: App\Game\Infrastructure\Repository\DoctrineTypes\PlayerIdType
            historyId: App\Game\Infrastructure\Repository\DoctrineTypes\HistoryIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Game:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/mappings'
                prefix: 'App\Game\Domain\Model'
